version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${APP_PORT:-8080}:${APP_PORT}
    environment:
      - APP_NAME=$APP_NAME
      - APP_PORT=$APP_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DRIVER=$POSTGRES_DRIVER
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    hostname: $POSTGRES_HOST
    tty: true
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT}
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./_scripts/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: